name: myriad_bus_scheduler
description: Bus Scheduling application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  provider: ^5.0.0
  dartz: ^0.9.2
  get_it: ^6.1.1
  google_maps_flutter: ^2.0.6
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  string_validator: ^0.3.0
  lottie: ^1.0.1
  #mockito: ^5.0.5






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

